### ISSUE TITLE
Bug with request creation 

### ISSUE THREAD

**Issue by knewbury01** [CMPUT301F16T04/Ridr#11]
**Bug description:**

Creating a request in the RiderMainView attempts to add a request to a rider's list of requests. The arraylists are currently null because we dont store the list attributes yet in the server. 

**Possible for now fix:** 

check if the attribute is null before adding.

**Possible fix for later:**

define a sort of constructor for the Rider that takes a jsonObject (like we did for requests) and initialize/populate its array attributes every time that the rider object is fetched from server. (maybe not best, there are likely other solutions?).

**Steps to replicate:**

1) navigate to RiderMainView (aka sign in as rider)
2) fill in field to create request and press button

**Comment by justinbarclay** [comment]
I like your fix, but I don't think we need to populate it's request or ride attributes ahead of time. I think this is something that could be done on their respective pages. IE When the Rider looks for their rides or their requests.

**Comment by MarcOlivierLajeunesse** [comment]
So to fix this bug, a rider shouldn't save a list of request. (are we still waiting for feedback from Stephen before committing to this, as it's not as OO as it could be?)

**Comment by knewbury01** [comment]
Clarified with Stephen that users do not need to keep an attribute that is their list of requests or a list of rides. We can remove these from our objects and do not have to worry about storing and updating these. Issue resolved!

**Comment by justinbarclay** [comment]
Didn't I all ready confirm this with him and then let everyone in our group know?

**Comment by knewbury01** [comment]
Sorry when I say clarified, I mean as a whole (which was actually just @justinbarclay), then wanted to comment and close the issue for clarity sake.
