### ISSUE TITLE
US 08.01.01 As an driver, I want to see requests that I already accepted while offline.

### ISSUE THREAD

**Issue by jferris72** [CMPUT301F16T04/Ridr#15]

**Comment by skaefer143** [comment]
Justin have you started on this? Because I'm not sure how you're going to do it without the Driver Request list, which hasn't actually been made yet haha

**Comment by jferris72** [comment]
Hey uh no I haven't started quite yet I guess I figured I could just test
by trying to lookup the requests by keyword or something while offline. I'm
not entirely sure it just seemed like the offline part might be interesting
to try to implement :P

**Comment by skaefer143** [comment]
Yeah I guess you could work with the controllers and stuff, so it's not a huge deal. I'm in the middle of implementing it so it'll be done eventually

**Comment by skaefer143** [comment]
Okay I'm done Justin, if you want to start working on this, then I'd say just look at my branch (driverRequestList) and look at the RequestsFromRiders view. Maybe review it first and make sure it looks good, and make another branch. 

Then what you'll basically have to do is while we're online, every time the elastic search query goes through to get requests associated with that driver, save it to a file. Then have a check in onStart whether or not we're online and have connectivity, and if we don't, load up the file. And maybe in the title have it say "Offline" or something.
I think that's how this would work
