### ISSUE TITLE
US 5.02.01 - Driver Request List

### ISSUE THREAD

**Issue by skaefer143** [CMPUT301F16T04/Ridr#16]
As a driver, I want to view a list of things I have accepted that are pending, each request with its description, and locations.

Will be making menu button on the Search Results View, with an option that leads to the RequestsFromRiders view. Shows all Requests that the Driver has agreed to fulfill.

**Comment by skaefer143** [comment]
Fully Implemented, and works. Tests are not done, not sure how to test the database.

**Comment by justinbarclay** [comment]
The Driver Ride view is done as well. It doesn't link anywhere yet, but aside from that it's good. I'm doing a code review with Kristy.

**Comment by justinbarclay** [comment]
I also think this means we have 5.02.01 and 5.03.01 looking for code reveiws.

**Comment by skaefer143** [comment]
Sounds good, I'm going to close this for now. But I'll mark in the requirements that the test is not finished
