### ISSUE TITLE
UI Storyboard Issue: Mixing requests and rides

### ISSUE THREAD

**Issue by mack1070101** [CMPUT301F16T04/Ridr#18]
![image](https://cloud.githubusercontent.com/assets/21961032/20470115/b9db1c04-af62-11e6-957a-f1f97a8d3bb9.png)

We need to revise this, so that we aren't mixing requests and rides. The new logic will be that a short press opens up the driver selection, and a long press allows you to cancel a ride.

I'm tagging you guys cause you dealt with the UI storyboarding, but if  you need me to take care of it, I definitely can.

**Comment by knewbury01** [comment]
ok , i can definitely fix this and put into master, one thing though, Im not entirely sure where the new ride displaying views will fit into the rest (like what view leads to them and what views do they go to), so if at some point someone could go over that with me I would greatly appreciate it!

**Comment by skaefer143** [comment]
I'd say you could probably put a "View Rides" button in the menu screen. You might have to make a new view for displaying the rides. Let's go over this in lab tonight, we need to make some major modifications to the UI anyways, because it's wrong for the drivers right now

**Comment by skaefer143** [comment]
Just updated UI, let me know what you think
